// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaDeConcepto.Api.Models;

namespace PruebaDeConcepto.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaDeConcepto.Api.Models.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Habitantes")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Pais");

                    b.HasData(
                        new
                        {
                            Id = new Guid("989558b2-33b6-45dc-aaa1-521f76f7330c"),
                            Habitantes = 46000000,
                            Nombre = "España"
                        },
                        new
                        {
                            Id = new Guid("b46a0038-cc00-4c5c-bc59-a953b6b47b1c"),
                            Habitantes = 83000000,
                            Nombre = "Alemania"
                        },
                        new
                        {
                            Id = new Guid("75bbb01d-6bc6-47e5-97d7-2044b3c84bc0"),
                            Habitantes = 65000000,
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = new Guid("1515be91-7940-42a6-a2c7-bd80c50fa2d0"),
                            Habitantes = 61000000,
                            Nombre = "Italia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
